spring.application.name=zanora-back
google.client.id=838764370475-t15eeibsqd7acjqtr9kgaa815c833mg4.apps.googleusercontent.com
server.port=8080
server.address=0.0.0.0
application.security.jwt.secret-key=fPk3PbD9PmWHKyRdiIWZ9pDQZtEXcBXkF4L5q0QGXZY=
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000
spring.datasource.url=jdbc:postgresql://localhost:5432/zanora
spring.datasource.username=postgres
spring.datasource.password=369963
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=HikariPool
app.admin.username=admin
spring.data.mongodb.uri=mongodb://localhost:27017/zanora_reviews
app.admin.email=admin@example.com

app.admin.password=Admin@123

app.admin.firstName=Admin
app.admin.lastName=User